# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='user',
            new_name='users',
        ),
        migrations.AddField(
            model_name='story',
            name='story_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='story_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
